#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.101                       #
#------------------------------------------------------------------------------#


WRKDIR = `pwd`

AS = as
CC = gcc
CPP = g++
F77 = f77
F9X = gfortran
LD = g++
AR = ar
RANLIB = ranlib
WINDRES = windres

INC = 
CFLAGS =  -Wall -fexceptions
RESINC = 
RCFLAGS = 
LIBDIR = 
LIB = 
LDFLAGS = 

INC_DEBUG =  $(INC)
CFLAGS_DEBUG =  $(CFLAGS) -g
RESINC_DEBUG =  $(RESINC)
RCFLAGS_DEBUG =  $(RCFLAGS)
LIBDIR_DEBUG =  $(LIBDIR)
LIB_DEBUG = $(LIB) /usr/lib64/libpthread.so /usr/lib64/libcrypt.so /usr/lib64/mysql/libmysqlclient.so libs/libjson_linux-gcc-4.7.2_libmt.a libs/libmysqlcppconn-static.a /usr/lib64/zqltNetD.so
LDFLAGS_DEBUG =  $(LDFLAGS)
OBJDIR_DEBUG = obj/Debug
DEP_DEBUG = 
OUT_DEBUG = bin/Debug/rmserx

INC_RELEASE =  $(INC)
CFLAGS_RELEASE =  $(CFLAGS) -O2
RESINC_RELEASE =  $(RESINC)
RCFLAGS_RELEASE =  $(RCFLAGS)
LIBDIR_RELEASE =  $(LIBDIR)
LIB_RELEASE = $(LIB) /usr/lib64/libpthread.so /usr/lib64/libcrypt.so /usr/lib64/mysql/libmysqlclient.so libs/libjson_linux-gcc-4.7.2_libmt.a libs/libmysqlcppconn-static.a /usr/lib64/zqltNet.so
LDFLAGS_RELEASE =  $(LDFLAGS) -s
OBJDIR_RELEASE = obj/Release
DEP_RELEASE = 
OUT_RELEASE = bin/Release/rmserx

OBJ_DEBUG = $(OBJDIR_DEBUG)/example/dzpk/mainDzpk.o $(OBJDIR_DEBUG)/example/dzpk/standard/custom.o $(OBJDIR_DEBUG)/example/dzpk/standard/dzpk.o $(OBJDIR_DEBUG)/example/dzpk/standard/dzpkActivity.o $(OBJDIR_DEBUG)/example/dzpk/standard/dzpkCard.o $(OBJDIR_DEBUG)/example/dzpk/standard/dzpkCustom.o $(OBJDIR_DEBUG)/example/dzpk/standard/dzpkParsePacket.o $(OBJDIR_DEBUG)/example/dzpk/standard/dzpkTask.o $(OBJDIR_DEBUG)/main.o $(OBJDIR_DEBUG)/core/loger/log.o $(OBJDIR_DEBUG)/example/dzpk/Start.o $(OBJDIR_DEBUG)/example/dzpk/championship/cps.o $(OBJDIR_DEBUG)/example/dzpk/championship/cpsCustom.o $(OBJDIR_DEBUG)/example/dzpk/championship/cpsRecord.o $(OBJDIR_DEBUG)/example/dzpk/championship/cpsUser.o $(OBJDIR_DEBUG)/example/dzpk/db/db_connect_pool.o $(OBJDIR_DEBUG)/example/dzpk/db/dzpkDb.o $(OBJDIR_DEBUG)/example/dzpk/db/MemData.o $(OBJDIR_DEBUG)/example/dzpk/dzpkPlay.o $(OBJDIR_DEBUG)/example/dzpk/dzpkUser.o $(OBJDIR_DEBUG)/http/HttpSocket.o $(OBJDIR_DEBUG)/udp/UdpServer.o $(OBJDIR_DEBUG)/udp/UdpBusiness.o

OBJ_RELEASE = $(OBJDIR_RELEASE)/example/dzpk/mainDzpk.o $(OBJDIR_RELEASE)/example/dzpk/standard/custom.o $(OBJDIR_RELEASE)/example/dzpk/standard/dzpk.o $(OBJDIR_RELEASE)/example/dzpk/standard/dzpkActivity.o $(OBJDIR_RELEASE)/example/dzpk/standard/dzpkCard.o $(OBJDIR_RELEASE)/example/dzpk/standard/dzpkCustom.o $(OBJDIR_RELEASE)/example/dzpk/standard/dzpkParsePacket.o $(OBJDIR_RELEASE)/example/dzpk/standard/dzpkTask.o $(OBJDIR_RELEASE)/main.o $(OBJDIR_RELEASE)/core/loger/log.o $(OBJDIR_RELEASE)/example/dzpk/Start.o $(OBJDIR_RELEASE)/example/dzpk/championship/cps.o $(OBJDIR_RELEASE)/example/dzpk/championship/cpsCustom.o $(OBJDIR_RELEASE)/example/dzpk/championship/cpsRecord.o $(OBJDIR_RELEASE)/example/dzpk/championship/cpsUser.o $(OBJDIR_RELEASE)/example/dzpk/db/db_connect_pool.o $(OBJDIR_RELEASE)/example/dzpk/db/dzpkDb.o $(OBJDIR_RELEASE)/example/dzpk/db/MemData.o $(OBJDIR_RELEASE)/example/dzpk/dzpkPlay.o $(OBJDIR_RELEASE)/example/dzpk/dzpkUser.o $(OBJDIR_RELEASE)/http/HttpSocket.o $(OBJDIR_RELEASE)/udp/UdpServer.o $(OBJDIR_RELEASE)/udp/UdpBusiness.o

all: Debug Release

clean: clean_Debug clean_Release

before_Debug: 
	test -d bin/Debug || mkdir -p bin/Debug
	test -d $(OBJDIR_DEBUG)/example/dzpk || mkdir -p $(OBJDIR_DEBUG)/example/dzpk
	test -d $(OBJDIR_DEBUG)/example/dzpk/standard || mkdir -p $(OBJDIR_DEBUG)/example/dzpk/standard
	test -d $(OBJDIR_DEBUG) || mkdir -p $(OBJDIR_DEBUG)
	test -d $(OBJDIR_DEBUG)/core/loger || mkdir -p $(OBJDIR_DEBUG)/core/loger
	test -d $(OBJDIR_DEBUG)/example/dzpk/championship || mkdir -p $(OBJDIR_DEBUG)/example/dzpk/championship
	test -d $(OBJDIR_DEBUG)/example/dzpk/db || mkdir -p $(OBJDIR_DEBUG)/example/dzpk/db
	test -d $(OBJDIR_DEBUG)/http || mkdir -p $(OBJDIR_DEBUG)/http
	test -d $(OBJDIR_DEBUG)/udp || mkdir -p $(OBJDIR_DEBUG)/udp

after_Debug: 

Debug: before_Debug out_Debug after_Debug

out_Debug: $(OBJ_DEBUG) $(DEP_DEBUG)
	#\cp -f ./libs/zqltNetD.so /usr/lib64/
	$(LD) $(LDFLAGS_DEBUG) $(LIBDIR_DEBUG) -o $(OUT_DEBUG) $(OBJ_DEBUG) $(LIB_DEBUG)

$(OBJDIR_DEBUG)/example/dzpk/mainDzpk.o: example/dzpk/mainDzpk.cpp
	$(CPP) $(CFLAGS_DEBUG) $(INC_DEBUG) -c -o $(OBJDIR_DEBUG)/example/dzpk/mainDzpk.o example/dzpk/mainDzpk.cpp

$(OBJDIR_DEBUG)/example/dzpk/standard/custom.o: example/dzpk/standard/custom.cpp
	$(CPP) $(CFLAGS_DEBUG) $(INC_DEBUG) -c -o $(OBJDIR_DEBUG)/example/dzpk/standard/custom.o example/dzpk/standard/custom.cpp

$(OBJDIR_DEBUG)/example/dzpk/standard/dzpk.o: example/dzpk/standard/dzpk.cpp
	$(CPP) $(CFLAGS_DEBUG) $(INC_DEBUG) -c -o $(OBJDIR_DEBUG)/example/dzpk/standard/dzpk.o example/dzpk/standard/dzpk.cpp

$(OBJDIR_DEBUG)/example/dzpk/standard/dzpkActivity.o: example/dzpk/standard/dzpkActivity.cpp
	$(CPP) $(CFLAGS_DEBUG) $(INC_DEBUG) -c -o $(OBJDIR_DEBUG)/example/dzpk/standard/dzpkActivity.o example/dzpk/standard/dzpkActivity.cpp

$(OBJDIR_DEBUG)/example/dzpk/standard/dzpkCard.o: example/dzpk/standard/dzpkCard.cpp
	$(CPP) $(CFLAGS_DEBUG) $(INC_DEBUG) -c -o $(OBJDIR_DEBUG)/example/dzpk/standard/dzpkCard.o example/dzpk/standard/dzpkCard.cpp

$(OBJDIR_DEBUG)/example/dzpk/standard/dzpkCustom.o: example/dzpk/standard/dzpkCustom.cpp
	$(CPP) $(CFLAGS_DEBUG) $(INC_DEBUG) -c -o $(OBJDIR_DEBUG)/example/dzpk/standard/dzpkCustom.o example/dzpk/standard/dzpkCustom.cpp

$(OBJDIR_DEBUG)/example/dzpk/standard/dzpkParsePacket.o: example/dzpk/standard/dzpkParsePacket.cpp
	$(CPP) $(CFLAGS_DEBUG) $(INC_DEBUG) -c -o $(OBJDIR_DEBUG)/example/dzpk/standard/dzpkParsePacket.o example/dzpk/standard/dzpkParsePacket.cpp

$(OBJDIR_DEBUG)/example/dzpk/standard/dzpkTask.o: example/dzpk/standard/dzpkTask.cpp
	$(CPP) $(CFLAGS_DEBUG) $(INC_DEBUG) -c -o $(OBJDIR_DEBUG)/example/dzpk/standard/dzpkTask.o example/dzpk/standard/dzpkTask.cpp

$(OBJDIR_DEBUG)/main.o: main.cpp
	$(CPP) $(CFLAGS_DEBUG) $(INC_DEBUG) -c -o $(OBJDIR_DEBUG)/main.o main.cpp

$(OBJDIR_DEBUG)/core/loger/log.o: core/loger/log.cpp
	$(CPP) $(CFLAGS_DEBUG) $(INC_DEBUG) -c -o $(OBJDIR_DEBUG)/core/loger/log.o core/loger/log.cpp

$(OBJDIR_DEBUG)/example/dzpk/Start.o: example/dzpk/Start.cpp
	$(CPP) $(CFLAGS_DEBUG) $(INC_DEBUG) -c -o $(OBJDIR_DEBUG)/example/dzpk/Start.o example/dzpk/Start.cpp

$(OBJDIR_DEBUG)/example/dzpk/championship/cps.o: example/dzpk/championship/cps.cpp
	$(CPP) $(CFLAGS_DEBUG) $(INC_DEBUG) -c -o $(OBJDIR_DEBUG)/example/dzpk/championship/cps.o example/dzpk/championship/cps.cpp

$(OBJDIR_DEBUG)/example/dzpk/championship/cpsCustom.o: example/dzpk/championship/cpsCustom.cpp
	$(CPP) $(CFLAGS_DEBUG) $(INC_DEBUG) -c -o $(OBJDIR_DEBUG)/example/dzpk/championship/cpsCustom.o example/dzpk/championship/cpsCustom.cpp

$(OBJDIR_DEBUG)/example/dzpk/championship/cpsRecord.o: example/dzpk/championship/cpsRecord.cpp
	$(CPP) $(CFLAGS_DEBUG) $(INC_DEBUG) -c -o $(OBJDIR_DEBUG)/example/dzpk/championship/cpsRecord.o example/dzpk/championship/cpsRecord.cpp

$(OBJDIR_DEBUG)/example/dzpk/championship/cpsUser.o: example/dzpk/championship/cpsUser.cpp
	$(CPP) $(CFLAGS_DEBUG) $(INC_DEBUG) -c -o $(OBJDIR_DEBUG)/example/dzpk/championship/cpsUser.o example/dzpk/championship/cpsUser.cpp

$(OBJDIR_DEBUG)/example/dzpk/db/db_connect_pool.o: example/dzpk/db/db_connect_pool.cpp
	$(CPP) $(CFLAGS_DEBUG) $(INC_DEBUG) -c -o $(OBJDIR_DEBUG)/example/dzpk/db/db_connect_pool.o example/dzpk/db/db_connect_pool.cpp

$(OBJDIR_DEBUG)/example/dzpk/db/dzpkDb.o: example/dzpk/db/dzpkDb.cpp
	$(CPP) $(CFLAGS_DEBUG) $(INC_DEBUG) -c -o $(OBJDIR_DEBUG)/example/dzpk/db/dzpkDb.o example/dzpk/db/dzpkDb.cpp
	
$(OBJDIR_DEBUG)/example/dzpk/db/MemData.o: example/dzpk/db/MemData.cpp
	$(CPP) $(CFLAGS_DEBUG) $(INC_DEBUG) -c -o $(OBJDIR_DEBUG)/example/dzpk/db/MemData.o example/dzpk/db/MemData.cpp

$(OBJDIR_DEBUG)/example/dzpk/dzpkPlay.o: example/dzpk/dzpkPlay.cpp
	$(CPP) $(CFLAGS_DEBUG) $(INC_DEBUG) -c -o $(OBJDIR_DEBUG)/example/dzpk/dzpkPlay.o example/dzpk/dzpkPlay.cpp

$(OBJDIR_DEBUG)/example/dzpk/dzpkUser.o: example/dzpk/dzpkUser.cpp
	$(CPP) $(CFLAGS_DEBUG) $(INC_DEBUG) -c -o $(OBJDIR_DEBUG)/example/dzpk/dzpkUser.o example/dzpk/dzpkUser.cpp

$(OBJDIR_DEBUG)/http/HttpSocket.o: http/HttpSocket.cpp
	$(CPP) $(CFLAGS_DEBUG) $(INC_DEBUG) -c -o $(OBJDIR_DEBUG)/http/HttpSocket.o http/HttpSocket.cpp

$(OBJDIR_DEBUG)/udp/UdpServer.o: udp/UdpServer.cpp
	$(CPP) $(CFLAGS_DEBUG) $(INC_DEBUG) -c -o $(OBJDIR_DEBUG)/udp/UdpServer.o udp/UdpServer.cpp

$(OBJDIR_DEBUG)/udp/UdpBusiness.o: udp/UdpBusiness.cpp
	$(CPP) $(CFLAGS_DEBUG) $(INC_DEBUG) -c -o $(OBJDIR_DEBUG)/udp/UdpBusiness.o udp/UdpBusiness.cpp


clean_Debug: 
	rm -f $(OBJ_DEBUG) $(OUT_DEBUG)
	#rm -rf bin/Debug
	rm -rf $(OBJDIR_DEBUG)/example/dzpk
	rm -rf $(OBJDIR_DEBUG)/example/dzpk/standard
	rm -rf $(OBJDIR_DEBUG)
	rm -rf $(OBJDIR_DEBUG)/core/loger
	rm -rf $(OBJDIR_DEBUG)/example/dzpk/championship
	rm -rf $(OBJDIR_DEBUG)/example/dzpk/db
	rm -rf $(OBJDIR_DEBUG)/http/
	rm -rf $(OBJDIR_DEBUG)/udp/

before_Release: 
	test -d bin/Release || mkdir -p bin/Release
	test -d $(OBJDIR_RELEASE)/example/dzpk || mkdir -p $(OBJDIR_RELEASE)/example/dzpk
	test -d $(OBJDIR_RELEASE)/example/dzpk/standard || mkdir -p $(OBJDIR_RELEASE)/example/dzpk/standard
	test -d $(OBJDIR_RELEASE) || mkdir -p $(OBJDIR_RELEASE)
	test -d $(OBJDIR_RELEASE)/core/loger || mkdir -p $(OBJDIR_RELEASE)/core/loger
	test -d $(OBJDIR_RELEASE)/example/dzpk/championship || mkdir -p $(OBJDIR_RELEASE)/example/dzpk/championship
	test -d $(OBJDIR_RELEASE)/example/dzpk/db || mkdir -p $(OBJDIR_RELEASE)/example/dzpk/db
	test -d $(OBJDIR_RELEASE)/http || mkdir -p $(OBJDIR_RELEASE)/http
	test -d $(OBJDIR_RELEASE)/udp || mkdir -p $(OBJDIR_RELEASE)/udp

after_Release: 

Release: before_Release out_Release after_Release

out_Release: $(OBJ_RELEASE) $(DEP_RELEASE)
	#\cp -f ./libs/zqltNet.so /usr/lib64/
	$(LD) $(LDFLAGS_RELEASE) $(LIBDIR_RELEASE) -o $(OUT_RELEASE) $(OBJ_RELEASE) $(LIB_RELEASE)

$(OBJDIR_RELEASE)/example/dzpk/mainDzpk.o: example/dzpk/mainDzpk.cpp
	$(CPP) $(CFLAGS_RELEASE) $(INC_RELEASE) -c -o $(OBJDIR_RELEASE)/example/dzpk/mainDzpk.o example/dzpk/mainDzpk.cpp

$(OBJDIR_RELEASE)/example/dzpk/standard/custom.o: example/dzpk/standard/custom.cpp
	$(CPP) $(CFLAGS_RELEASE) $(INC_RELEASE) -c -o $(OBJDIR_RELEASE)/example/dzpk/standard/custom.o example/dzpk/standard/custom.cpp

$(OBJDIR_RELEASE)/example/dzpk/standard/dzpk.o: example/dzpk/standard/dzpk.cpp
	$(CPP) $(CFLAGS_RELEASE) $(INC_RELEASE) -c -o $(OBJDIR_RELEASE)/example/dzpk/standard/dzpk.o example/dzpk/standard/dzpk.cpp

$(OBJDIR_RELEASE)/example/dzpk/standard/dzpkActivity.o: example/dzpk/standard/dzpkActivity.cpp
	$(CPP) $(CFLAGS_RELEASE) $(INC_RELEASE) -c -o $(OBJDIR_RELEASE)/example/dzpk/standard/dzpkActivity.o example/dzpk/standard/dzpkActivity.cpp

$(OBJDIR_RELEASE)/example/dzpk/standard/dzpkCard.o: example/dzpk/standard/dzpkCard.cpp
	$(CPP) $(CFLAGS_RELEASE) $(INC_RELEASE) -c -o $(OBJDIR_RELEASE)/example/dzpk/standard/dzpkCard.o example/dzpk/standard/dzpkCard.cpp

$(OBJDIR_RELEASE)/example/dzpk/standard/dzpkCustom.o: example/dzpk/standard/dzpkCustom.cpp
	$(CPP) $(CFLAGS_RELEASE) $(INC_RELEASE) -c -o $(OBJDIR_RELEASE)/example/dzpk/standard/dzpkCustom.o example/dzpk/standard/dzpkCustom.cpp

$(OBJDIR_RELEASE)/example/dzpk/standard/dzpkParsePacket.o: example/dzpk/standard/dzpkParsePacket.cpp
	$(CPP) $(CFLAGS_RELEASE) $(INC_RELEASE) -c -o $(OBJDIR_RELEASE)/example/dzpk/standard/dzpkParsePacket.o example/dzpk/standard/dzpkParsePacket.cpp

$(OBJDIR_RELEASE)/example/dzpk/standard/dzpkTask.o: example/dzpk/standard/dzpkTask.cpp
	$(CPP) $(CFLAGS_RELEASE) $(INC_RELEASE) -c -o $(OBJDIR_RELEASE)/example/dzpk/standard/dzpkTask.o example/dzpk/standard/dzpkTask.cpp

$(OBJDIR_RELEASE)/main.o: main.cpp
	$(CPP) $(CFLAGS_RELEASE) $(INC_RELEASE) -c -o $(OBJDIR_RELEASE)/main.o main.cpp

$(OBJDIR_RELEASE)/core/loger/log.o: core/loger/log.cpp
	$(CPP) $(CFLAGS_RELEASE) $(INC_RELEASE) -c -o $(OBJDIR_RELEASE)/core/loger/log.o core/loger/log.cpp

$(OBJDIR_RELEASE)/example/dzpk/Start.o: example/dzpk/Start.cpp
	$(CPP) $(CFLAGS_RELEASE) $(INC_RELEASE) -c -o $(OBJDIR_RELEASE)/example/dzpk/Start.o example/dzpk/Start.cpp

$(OBJDIR_RELEASE)/example/dzpk/championship/cps.o: example/dzpk/championship/cps.cpp
	$(CPP) $(CFLAGS_RELEASE) $(INC_RELEASE) -c -o $(OBJDIR_RELEASE)/example/dzpk/championship/cps.o example/dzpk/championship/cps.cpp

$(OBJDIR_RELEASE)/example/dzpk/championship/cpsCustom.o: example/dzpk/championship/cpsCustom.cpp
	$(CPP) $(CFLAGS_RELEASE) $(INC_RELEASE) -c -o $(OBJDIR_RELEASE)/example/dzpk/championship/cpsCustom.o example/dzpk/championship/cpsCustom.cpp

$(OBJDIR_RELEASE)/example/dzpk/championship/cpsRecord.o: example/dzpk/championship/cpsRecord.cpp
	$(CPP) $(CFLAGS_RELEASE) $(INC_RELEASE) -c -o $(OBJDIR_RELEASE)/example/dzpk/championship/cpsRecord.o example/dzpk/championship/cpsRecord.cpp

$(OBJDIR_RELEASE)/example/dzpk/championship/cpsUser.o: example/dzpk/championship/cpsUser.cpp
	$(CPP) $(CFLAGS_RELEASE) $(INC_RELEASE) -c -o $(OBJDIR_RELEASE)/example/dzpk/championship/cpsUser.o example/dzpk/championship/cpsUser.cpp

$(OBJDIR_RELEASE)/example/dzpk/db/db_connect_pool.o: example/dzpk/db/db_connect_pool.cpp
	$(CPP) $(CFLAGS_RELEASE) $(INC_RELEASE) -c -o $(OBJDIR_RELEASE)/example/dzpk/db/db_connect_pool.o example/dzpk/db/db_connect_pool.cpp

$(OBJDIR_RELEASE)/example/dzpk/db/dzpkDb.o: example/dzpk/db/dzpkDb.cpp
	$(CPP) $(CFLAGS_RELEASE) $(INC_RELEASE) -c -o $(OBJDIR_RELEASE)/example/dzpk/db/dzpkDb.o example/dzpk/db/dzpkDb.cpp
	
$(OBJDIR_RELEASE)/example/dzpk/db/MemData.o: example/dzpk/db/MemData.cpp
	$(CPP) $(CFLAGS_RELEASE) $(INC_RELEASE) -c -o $(OBJDIR_RELEASE)/example/dzpk/db/MemData.o example/dzpk/db/MemData.cpp

$(OBJDIR_RELEASE)/example/dzpk/dzpkPlay.o: example/dzpk/dzpkPlay.cpp
	$(CPP) $(CFLAGS_RELEASE) $(INC_RELEASE) -c -o $(OBJDIR_RELEASE)/example/dzpk/dzpkPlay.o example/dzpk/dzpkPlay.cpp

$(OBJDIR_RELEASE)/example/dzpk/dzpkUser.o: example/dzpk/dzpkUser.cpp
	$(CPP) $(CFLAGS_RELEASE) $(INC_RELEASE) -c -o $(OBJDIR_RELEASE)/example/dzpk/dzpkUser.o example/dzpk/dzpkUser.cpp

$(OBJDIR_RELEASE)/http/HttpSocket.o: http/HttpSocket.cpp
	$(CPP) $(CFLAGS_RELEASE) $(INC_RELEASE) -c -o $(OBJDIR_RELEASE)/http/HttpSocket.o http/HttpSocket.cpp

$(OBJDIR_RELEASE)/udp/UdpServer.o: udp/UdpServer.cpp
	$(CPP) $(CFLAGS_RELEASE) $(INC_RELEASE) -c -o $(OBJDIR_RELEASE)/udp/UdpServer.o udp/UdpServer.cpp

$(OBJDIR_RELEASE)/udp/UdpBusiness.o: udp/UdpBusiness.cpp
	$(CPP) $(CFLAGS_RELEASE) $(INC_RELEASE) -c -o $(OBJDIR_RELEASE)/udp/UdpBusiness.o udp/UdpBusiness.cpp

clean_Release: 
	rm -f $(OBJ_RELEASE) $(OUT_RELEASE)
	#rm -rf bin/Release
	rm -rf $(OBJDIR_RELEASE)/example/dzpk
	rm -rf $(OBJDIR_RELEASE)/example/dzpk/standard
	rm -rf $(OBJDIR_RELEASE)
	rm -rf $(OBJDIR_RELEASE)/core/loger
	rm -rf $(OBJDIR_RELEASE)/example/dzpk/championship
	rm -rf $(OBJDIR_RELEASE)/example/dzpk/db
	rm -rf $(OBJDIR_RELEASE)/http
	rm -rf $(OBJDIR_RELEASE)/udp

.PHONY: before_Debug after_Debug clean_Debug before_Release after_Release clean_Release

